version: "3"
 
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python3 manage.py wait_for_db &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db
      - worker
  db:
    image: postgres:16-alpine
    env_file:
      - .env
  redis:
    image: redis:alpine
  worker:
    restart: always
    build:
      context: .
    command: celery -A config.celery:app worker --concurrency 1 -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db
