# Generated by Django 5.0 on 2023-12-23 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSetTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("failed", "Failed"),
                            ("ready", "Ready"),
                        ],
                        default="processing",
                        max_length=63,
                    ),
                ),
                ("file", models.FileField(null=True, upload_to="uploads/%Y/%m/%d/")),
            ],
        ),
        migrations.CreateModel(
            name="DataType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_name", models.CharField(max_length=63)),
                ("order", models.PositiveIntegerField()),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Schema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63)),
                (
                    "delimiter",
                    models.CharField(
                        choices=[
                            (",", "Comma (,)"),
                            (";", "Semicolon (;)"),
                            ("|", "Bar (|)"),
                            ("\t", "Tab"),
                            (" ", "Space"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "quotechar",
                    models.CharField(
                        choices=[('"', 'Double-quote (")'), ("'", "Single-quote (')")],
                        max_length=1,
                    ),
                ),
                ("modified", models.DateField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="DomainName",
            fields=[
                (
                    "datatype_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.datatype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("app.datatype",),
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "datatype_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.datatype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("app.datatype",),
        ),
        migrations.CreateModel(
            name="FullName",
            fields=[
                (
                    "datatype_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.datatype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("app.datatype",),
        ),
        migrations.CreateModel(
            name="Integer",
            fields=[
                (
                    "datatype_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.datatype",
                    ),
                ),
                ("from_bound", models.IntegerField()),
                ("to_bound", models.IntegerField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("app.datatype",),
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "datatype_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.datatype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("app.datatype",),
        ),
    ]
