# Generated by Django 5.0 on 2023-12-28 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datatype",
            options={"ordering": ("order",)},
        ),
        migrations.AlterModelOptions(
            name="domainname",
            options={"base_manager_name": "objects", "verbose_name": "Domain Name"},
        ),
        migrations.AlterModelOptions(
            name="email",
            options={"base_manager_name": "objects", "verbose_name": "Email"},
        ),
        migrations.AlterModelOptions(
            name="fullname",
            options={"base_manager_name": "objects", "verbose_name": "Full Name"},
        ),
        migrations.AlterModelOptions(
            name="integer",
            options={"base_manager_name": "objects", "verbose_name": "Integer"},
        ),
        migrations.AlterModelOptions(
            name="job",
            options={"base_manager_name": "objects", "verbose_name": "Job"},
        ),
        migrations.AlterField(
            model_name="datatype",
            name="schema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="app.schema",
            ),
        ),
    ]
