# Generated by Django 5.0 on 2023-12-30 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_datatype_options_alter_domainname_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasettask",
            name="created",
            field=models.DateField(
                auto_now_add=True, default=datetime.date(2023, 12, 30)
            ),
            preserve_default=False,
        ),
    ]
